### ISSUE TITLE
initial deploy fails 

### ISSUE THREAD

**Issue by khabbabs** [EngineerBetter/control-tower#1]
Do I need to create a bucket before deploying? documentations isn't very clear. 

error

./control-tower deploy poc_concourse --iaas aws

error getting initial config before deploy: [error persisting new config after setting values [NoSuchBucket: The specified bucket does not exist

**Comment by crsimmons** [comment]
Hi @khabbabs 

You don't need to create the bucket before deploying. `control-tower` will take care of everything for you. I'm not sure why you're seeing this error. To help us figure it out can you please share the release of control tower that you are using and confirm that the user who's keys you are deploying with has [these permissions](https://github.com/EngineerBetter/control-tower#using-a-dedicated-aws-iam-account) as a minimum?

**Comment by crsimmons** [comment]
This issue has been inactive for a while so I'm going to close it. If you are still having an issue feel free to reopen it.
