### ISSUE TITLE
Add support for bitbucket login

### ISSUE THREAD

**Issue by nbrys** [EngineerBetter/control-tower#13]
Add support for authentication with Bitbucket.

**Comment by crsimmons** [comment]
@nbrys Thanks for suggesting this!

I'll add a story to our backlog but we have limited engineering resources at the moment so there may be a delay in getting it done. It also looks like there _might_ be a [problem with bitbucket auth in Concourse 5.1 currently](https://discuss.concourse-ci.org/t/concourse-5-1-teams-dont-seem-to-work-with-bitbucket/1324).

If you want to see it implemented sooner we would welcome PRs.

**Comment by huiz-psma** [comment]
Need this feature too. We are stuck in the older version and would like to upgrade to Concourse 5 asap.

**Comment by cyberox** [comment]
I created a PR for adding bitbucket support. #86

**Comment by cyberox** [comment]
@crsimmons you can close this issue.

**Comment by crsimmons** [comment]
Whoops forgot about the issue. This was released in https://github.com/EngineerBetter/control-tower/releases/tag/0.14.0.
