### ISSUE TITLE
Add Support for AWS Sub-Account roles

### ISSUE THREAD

**Issue by zgagnon** [EngineerBetter/control-tower#16]
AWS Account credentials (access_key_id and secret_access_key) can be supplemented with a role arn to provide access to sub-accounts in AWS. If Control Tower is deployed to one of these sub-accounts, the self-update job fails because it can not find the S3 bucket. Can we add support for this account management feature?

**Comment by danyoung** [comment]
Thanks for letting us know about this behaviour in AWS sub accounts @zgagnon . Our team is mostly out with customers at the moment, but we'll create a story and discuss it.
