### ISSUE TITLE
Docker image put task hung for a long time.

### ISSUE THREAD

**Issue by huiz-psma** [EngineerBetter/control-tower#190]
Trying to optimise the pipeline and found it. In the screenshot, the step before waiting for docker to come up took almost 4 minutes. Looking through the history, the delay is always there, ranging from 2 mins to 4 mins. Can I get some help to remove the delay if possible? Thank you.

![Screen Shot 2022-04-18 at 1 10 15 pm](https://user-images.githubusercontent.com/42223429/163748698-35192d08-b519-4e7b-b192-45aa16709685.png)
 
my config for the two steps:
`

       - get: docker-image-platform-code
          params:
            save: true
        - put: docker-image-platform-code
            params:
            build: build
            tag_as_latest: true
            tag_file: build/git_master_hash
            timeout: 15m
            cache: true
            load_base: docker-image-platform-base
            cache_from: docker-image-platform-code
`

**Comment by DanielJonesEB** [comment]
@andy-paine was there a PR to Concourse that logged when volumes were being streamed between workers? If so, did it get merged?

**Comment by andy-paine** [comment]
Yep that was released in Concourse 7.7.0 https://github.com/concourse/concourse/releases#8031

You'll need to be running [Control Tower 0.17.30](https://github.com/EngineerBetter/control-tower/releases/tag/0.17.30) or higher to see it

**Comment by DanielJonesEB** [comment]
@huiz-psma Which version of Control Tower and Concourse are you using? It could be that the delay you're seeing is where Concourse is moving volumes (container images and previously-pulled resources) from one worker to another.

I think this is unlikely to be a Control Tower-specific issue, and is more likely Concourse behaviour.

**Comment by huiz-psma** [comment]
@DanielJonesEB We are using 0.17.30, but I don't see any relevant logs

**Comment by DanielJonesEB** [comment]
Ah, okay. In that case I suggest that this is probably generic Concourse behaviour, and you'd be best of raising the issue over there. We'll re-open this issue if there's evidence that it's something specific about the way Control Tower is configured. Best of luck!

**Comment by andy-paine** [comment]
It also may be that using the docker-image resource (which runs as privileged) is slowing things down as the volume must be recursively `chown`-d in order to be usable in the privileged container https://github.com/concourse/concourse/discussions/6458#discussioncomment-303283.

The preferred way of building container images nowadays is using https://github.com/concourse/oci-build-task to build the image and `put` it with the registry-image resource
