### ISSUE TITLE
Error from "control-tower info": bosh orchestrator down, unable to diagnose

### ISSUE THREAD

**Issue by RichardBradley** [EngineerBetter/control-tower#217]
Hi,

Our control-tower Concourse instance seems to have died today and I'm struggling to diagnose what's wrong or to attempt a fix.

Everything in [the Troubleshooting docs](https://github.com/EngineerBetter/control-tower/blob/master/docs/troubleshooting.md) seems to start with `control-tower info`, but that is failing for me:

```
$ control-tower info --iaas AWS --env my.server
Error getting BOSH instances: Error [exit status 1] running `bosh instances`. stdout: [{
    "Tables": null,
    "Blocks": null,
    "Lines": [
        "Fetching info:\n  Performing request GET 'https://54.77.80.216:25555/info':\n    Performing GET request:\n      Retry: \u003cnil cause\u003e",
        "Exit code 1"
    ]
}]

$ curl -k  https://54.77.80.216:25555/info
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I have tried rebooting the Bosh Orchestrator VM, but it didn't change things.

Is there any way to get shell on the Bosh Orchestrator VM to see what's up with it? I tried SSH but got `Permission denied (publickey).` without a password prompt. Can I break into it from the EC2 console somehow?

Thanks,

Rich

**Comment by RichardBradley** [comment]
After poking at things for ages, I noticed that the RDS psql instance had run out of disk space. I increased that in the AWS console and the system recovered.

So I have a fix. I would appreciate any comments on how I can get shell on the BOSH server or how to diagnose similar things in future, if anyone has any. I'll leave this issue open for a couple of days.

**Comment by crsimmons** [comment]
It's a "feature" of BOSH that you can't SSH to the director by default. The way around it is to add a special user to the vm which you can then SSH to. The official docs on this [can be found here](https://bosh.io/docs/jumpbox/).

For historical reasons that I can't remember we actually include this feature on GCP deployments but not on AWS. We can look at adding it to AWS as well.

I think the workaround is to add the ops in the GCP [jumpbox-user.yml](https://github.com/EngineerBetter/control-tower/blob/master/resource/assets/gcp/jumpbox-user.yml) to the [AWS custom-ops.yml](https://github.com/EngineerBetter/control-tower/blob/master/resource/assets/aws/custom-ops.yml) then build a local version of Control Tower and deploy with it. Then you should be able to pull the private key from the config.json in S3 and ssh with `ssh -i key.pem jumpbox@$BOSH_ENVIRONMENT`.
