### ISSUE TITLE
100% CPU reported by grafana concourse dashboard with no reason

### ISSUE THREAD

**Issue by lorands** [EngineerBetter/control-tower#24]
Grafana concourse dashboard reports 100% CPU for some time now (was the same with concourse-up), and it does not change. 
I've checked in AWS web, workers, bosh EC2 instances, RDS as well, and all of them are doing more than fine (usually bellow 40% at peak) according to AWS monitoring.
I've ssh to a web node with bosh: htop reports cpu varying between 10-50 at average, rearly hitting 100%. Load is now: 2.20 2.16 2.11. 
I have a default setup with 2 workers in AWS. On latest version, with concourse 5.2.0. 
Otherwise everything is working as expected, it is just a bit annoying. 
![Screenshot_20190607_122854](https://user-images.githubusercontent.com/1382237/59098156-dad69c00-891f-11e9-9a73-6e96867542fd.png)

**Comment by crsimmons** [comment]
I'm not sure how to reproduce this. It seems really weird that it spiked to 100% so suddenly then stayed there. That graph is for the web vm which is a t2 instance by defaullt. Could it be that your instance ran out of credits so is getting throttled by AWS? You should be able to check this in the EC2 console.

**Comment by lorands** [comment]
After upgrading the web node to t2.medium this does not occur any more.
For the record: AWS did not reported any issue, and as I defined the AWS monitoring reported low usage usually, as well as the boxes. But concourse was slow from time to time. Now with upgraded web node everything looks ok from this perspective.

**Comment by crsimmons** [comment]
I don't have a lot of faith in our old grafana dashboard. 0.8.1 introduced an improved dashboard.

Closing this issue as scaling the web node appears to have resolved things anyway.
