### ISSUE TITLE
Unable to SSH into my web node

### ISSUE THREAD

**Issue by nbrys** [EngineerBetter/control-tower#26]
When deploying a concourse on AWS using control tower. Terraform gives back the public key used for accessing the web node. After allowing access on port 22 from my IP to the webnode, I use the following command:

`ssh -i concourse-key.pem root@<ip-addresss>` or `ssh -i concourse-key.pem ubuntu@<ip-addresss>`

But I can't access the VM. This is the error i get:

`Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Received disconnect from <ip-addresss> port 22:2: Too many authentication failures
Disconnected from <ip-addresss> port 22`

**Comment by crsimmons** [comment]
Hi @nbrys 

We don't intend for nor test the ability to SSH directly to VMs in your Control Tower deployment. The intended way to do this is with BOSH.

You can export the env vars needed for BOSH with

```sh
eval "$(control-tower info --iaas aws --region <your-region> --env <your-deployment-name)"
```
then you can SSH to the web node with `bosh ssh web`.
