### ISSUE TITLE
Auto update pipeline fails

### ISSUE THREAD

**Issue by nbrys** [EngineerBetter/control-tower#27]
When running the auto update pipeline, we get the following error:

`+ cd control-tower-release
+ chmod +x control-tower-linux-amd64
+ ./control-tower-linux-amd64 deploy concourse-id
error ensuring config bucket exists before deploy: [error determining if bucket [] exists: [InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, HeadBucketInput.Bucket.
]]`

**Comment by lextoumbourou** [comment]
Also experiencing this error with latest release: `0.8.2`:

```
./control-tower-darwin-amd64 deploy --iaas AWS --region ap-southeast-2 some-id
error ensuring config bucket exists before deploy: [error determining if bucket [] exists: [InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, HeadBucketInput.Bucket.
```

**Comment by gramidt** [comment]
@crsimmons - Would you be able to provide insight into the error listed above? I am also experiencing this issue and would be more than happy to help identify the root cause and provide a PR if needed. Thank you in advance for all of your help!

**Comment by gramidt** [comment]
@crsimmons @nbrys @lextoumbourou  - I found the bug and I will provide a PR shortly.
