### ISSUE TITLE
No dashboard available in grafana

### ISSUE THREAD

**Issue by nbrys** [EngineerBetter/control-tower#28]
After deploying a new concourse build using the latest version of control tower, we have no dashboard in grafana.

**Comment by Turbots** [comment]
I'm having the same issue, installed today

**Comment by crsimmons** [comment]
Thanks @nbrys and @Turbots for raising this. I noticed the same last week on our internal Concourse deployment. I think it's an issue with the grafana release we use where a deprecated feature is being used and must have been removed in the latest release of grafana. I'm just about to PR a fix to the release which should fix it in Control Tower once it gets merged and released.

In the meantime you can copy the dashboard json from https://github.com/EngineerBetter/control-tower/blob/master/bosh/assets/grafana_dashboard.yml and use it to create a new dashboard in the grafana UI.

**Comment by crsimmons** [comment]
This issue was resolved in [0.7.3](https://github.com/EngineerBetter/control-tower/releases/tag/0.7.3)

**Comment by RichardBradley** [comment]
I tried to create a dashboard from that yaml but got "panel with id 2 not found"
