### ISSUE TITLE
Suggestions for improvements in documentation

### ISSUE THREAD

**Issue by michaellihs** [EngineerBetter/control-tower#3]
Maybe it's due to me being a newb on GCP but I had some struggle figuring out, which APIs I have to activate for Control-Tower to spin up a Concourse setup on GCP. So maybe the following list (that I came up with) would be worth mentioning in the documentation:

* `gcloud services enable compute.googleapis.com`
* `gcloud services enable iam.googleapis.com`
* `gcloud services enable cloudresourcemanager.googleapis.com`
* `gcloud services enable sqladmin.googleapis.com`

**Comment by DanielJonesEB** [comment]
Thanks for highlighting this @michaellihs. Frustratingly we've got a story for this in our backlog so it should have been done already, but looks like for whatever reason it didn't get scheduled.

We'll add it to the README shortly.

**Comment by danyoung** [comment]
Now added. Thanks @michaellihs
