### ISSUE TITLE
GCP: --domain needs to reflect the FQDN and not the DNS zone

### ISSUE THREAD

**Issue by npintaux** [EngineerBetter/control-tower#32]
Hello,
the current documentation states:

_control-tower deploy --domain chimichanga.engineerbetter.com chimichanga
In the example above control-tower will search for a hosted zone that matches chimichanga.engineerbetter.com or engineerbetter.com and add a record to the longest match (chimichanga.engineerbetter.com in this example)._

In GCP, if I create a DNS zone pointing to chimichanga.engineerbetter.com, then control-tower will actually create a record such as:

         chimichanga.engineerbetter.com.chimichanga.engineerbetter.com

It works ok if the DNS zone corresponds to engineerbetter.com. It will then add a record such as:

         chimichanga.engineerbetter.com

**Comment by crsimmons** [comment]
Sorry for the delay. This should be resolved in (0.8.3)[https://github.com/EngineerBetter/control-tower/releases/tag/0.8.3].
