### ISSUE TITLE
`control-tower info` should provide login info for Concourse

### ISSUE THREAD

**Issue by michaellihs** [EngineerBetter/control-tower#4]
After testing Control Tower a little more, I stumbled over the use case where I wanted to script the login to Concourse after `control-tower deploy` finished.

The log output of the deployment contains the line

```
DEPLOY SUCCESSFUL. Log in with:
fly --target concourse login --insecure --concourse-url...
```

However, when I want to get the Concourse login information after I ran the deploy command, I currently don't see a way of getting this from `control-tower`. `control-tower info...` does not contain the Concourse credentials.

For automation purposes, it would be extremely helpful to either have the Concourse credentials in Credhub after the deployment (as described in #2) or being able to use `control-tower info` to get it after the deployment.

**Comment by crsimmons** [comment]
Hey @michaellihs,

You can accomplish this with the `--json` flag on `control-tower info`. For example the following will get you the password:

`control-tower info --iaas aws --json deployment | jq -r '.config.concourse_password'`

The username is always `admin`.

**Comment by michaellihs** [comment]
Thanks a lot for the `--json` tip, that does the trick!

My problem was that I used the `--env` flag (without knowing that this changes the output).

```bash
$  control-tower info --region europe-west1 --iaas gcp --env concourse

export BOSH_ENVIRONMENT=...
export BOSH_GW_HOST=...
export BOSH_CA_CERT=...
export BOSH_DEPLOYMENT=concourse
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=...
export BOSH_GW_USER=jumpbox
export BOSH_GW_PRIVATE_KEY=...
export CREDHUB_SERVER=...
export CREDHUB_CA_CERT=...
export CREDHUB_CLIENT=credhub_admin
export CREDHUB_SECRET=...
export NAMESPACE=europe-west1
```

I am very happy with JSON  now :)

And btw: thanks for your immediate responses!!!

**Comment by crsimmons** [comment]
Great! I'm glad I could help :)

**Comment by msawant060** [comment]
Whenever I try running the command I am getting a error:
control-tower info --region ap-northeast-1 --iaas aws pcf-concourse

NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by msawant060** [comment]
> Whenever I try running the command I am getting a error:
> control-tower info --region ap-northeast-1 --iaas aws pcf-concourse
> 
> NoCredentialProviders: no valid providers in chain. Deprecated.
> For verbose messaging see aws.Config.CredentialsChainVerboseErrors

I just need to export my aws  use export AWS_ACCESS_KEY_ID=xxx and export AWS_SECRET_ACCESS_KEY=yyy before
