### ISSUE TITLE
Get shell on the worker instance?

### ISSUE THREAD

**Issue by RichardBradley** [EngineerBetter/control-tower#41]
Hi,

Do you know how I can ssh into the worker instance?
I am having "too many open files" and out of memory issues during my builds and I want to investigate.

Thanks,

Rich

**Comment by DanielJonesEB** [comment]
1. Install the BOSH CLI
1. `eval "$(control-tower info --iaas [AWS|GCP] --env <your-project-name>)"`

**Comment by RichardBradley** [comment]
Thanks, that worked. 

(I didn't need to change anything re (2))

**Comment by DanielJonesEB** [comment]
Cool. Step 2 is only needed if you're accessing it from a machine other than the one that deployed it.

**Comment by RichardBradley** [comment]
I think I might have been looking for `fly intercept`, actually.
https://concourse-ci.org/builds.html#fly-intercept

I want a shell inside my build environment.

I am trying to follow the example given at the above link:

```
$ fly -t example execute
$ fly -t example intercept --step build
```

I get:

```
$ fly -t my-project execute MYPROJ/my-build
error: the required flag `-c, --config' was not specified
```

I can't figure out what to pass for "--config", it's not covered in the Fly docs

**Comment by DanielJonesEB** [comment]
@RichardBradley you're accidentally running `execute` (which runs a task described the file provided by `--config`) instead of `intercept`.

**Comment by RichardBradley** [comment]
The link above said to run `execute` before `intercept`; I had assumed in order for there to be a build in progress that I could intercept?

I see to have gotten further as follows:

```
$ fly -t my-project builds
... list of recent builds, including valid "pipeline/job" values
$ fly -t my-project intercept -j "MYPIPELINE/my-job"
1: build #98, step: Test and Package, type: task
2: build #98, step: email, type: get
3: build #98, step: email, type: put
4: build #98, step: my-job, type: get
choose a container: 1
Backend error: Exit status: 500, message: {"Type":"ExecutableNotFoundError","Message":"exec failed: container_linux.go:345: starting container process cause
d \"exec: \\\"bash\\\": executable file not found in $PATH\"\n","Handle":"","ProcessID":"","Binary":""}
```

Any idea what that means and how to fix?

(Thanks for all your help here)

**Comment by RichardBradley** [comment]
Maybe my build container is missing `bash`? We have chosen `FROM node:10.16-alpine` for a docker base, which is super minimal. I'll check

**Comment by RichardBradley** [comment]
Yes, it looks like it: https://stackoverflow.com/questions/40944479/how-to-use-bash-with-an-alpine-based-docker-image/40944512

Can I get fly to use `sh` rather than `bash`?

**Comment by DanielJonesEB** [comment]
You certainly can:

```
fly [OPTIONS] hijack [hijack-OPTIONS] [command...]
```

where `[command...]` defaults to `/bin/bash`.

So either of these should work, depending on where `sh` exists in that image.

```
$ fly -t my-project intercept -j pipeline/job -- bin/sh
$ fly -t my-project intercept -j pipeline/job bin/sh
```

**Comment by RichardBradley** [comment]
Thanks!
