### ISSUE TITLE
GitHub auth not working

### ISSUE THREAD

**Issue by RichardBradley** [EngineerBetter/control-tower#52]
I want to use GitHub auth on my Concourse, but I can't figure out how.

I have deployed my concourse as follows:

    control-tower deploy --iaas AWS ci.example.com --domain ci.example.com --github-auth-client-secret xxx --github-auth-client-id xxx

I have configured my teams as follows:

```
$ cat main-team.yaml
roles:
- name: owner
  local:
    users: ["admin"]
- name: pipeline-operator
  github:
    orgs: ["MyOrgName"]
$ fly -t ci.example.com set-team -n main --config main-team.yaml
```

... but the concourse login page does not offer a GitHub login option.

Do you know what I have done wrong and how to debug or fix?

I tried logging into the "web" concourse server and I didn't see any github stuff in its env:

```
$ ps aux | grep conc
bosh_77+ 11383  0.0  0.0  12944  1020 pts/0    S+   16:01   0:00 grep --color=auto conc
vcap     12106  1.1  3.3 497052 67628 ?        S<sl Oct29  35:19 /var/vcap/packages/concourse/bin/concourse web
$ sudo cat /proc/12106/environ | grep -i githu
# (no match)

```

I was expecting to see the env vars "CONCOURSE_GITHUB_CLIENT_ID" and "CONCOURSE_GITHUB_CLIENT_SECRET" set there via `control-tower`.

**Comment by irbekrm** [comment]
Could this be related to #50 and also fixable by re-ordering flags before the deployment name?

**Comment by RichardBradley** [comment]
This is working for me now.
I don't remember what I changed, sorry.
