### ISSUE TITLE
Login to the Bosh or concourse web ec2

### ISSUE THREAD

**Issue by huiz-psma** [EngineerBetter/control-tower#53]
Hi,

We would like to login to the ec2 servers to install datadog agent. Can someone tell me which is the key to login to which server (bosh or the web node)? or is there a alternative way to send build metrics to datadog. I am aware of access to Grafana dashboard.

Thanks and regards,
Hui

**Comment by irbekrm** [comment]
Hi Hui,

Thanks for your question. I wouldn't recommend trying to manually install datadog agent on the EC2 servers. The Concourse that `control-tower` deploys is a bosh deployment, which means that the VMs and the processes running on them are managed entirely by bosh, for example, bosh could recreate the VMs if it detected some problems (i.e at infrastructure level) and your manual changes would be lost.

I see that the generally recommended way how to install datadog agent on bosh's VMs is using the datadog agent bosh release like described here https://github.com/DataDog/datadog-agent-boshrelease. I haven't tried changing the runtime config of the bosh director that is deployed by `control-tower` though, so I'm not sure if this has a chance to work.

If you want to access the Concourse VMs (`web` or `worker`) you can use the `control-tower` info command with `eval` like described [here](https://github.com/EngineerBetter/control-tower/blob/master/docs/info.md) to export bosh credentials and then `bosh ssh web` or `bosh ssh worker` or use any other bosh cli command. 

Let us know if we can be of any further help.

**Comment by irbekrm** [comment]
Closing this as it seems to have gone stale.
