### ISSUE TITLE
Slack Link Invalid

### ISSUE THREAD

**Issue by j-halbert** [EngineerBetter/control-tower#54]
This is no longer valid: https://join.slack.com/t/concourse-up/shared_invite/enQtNDMzNjY1MjczNDU3LTA1NzIxYTZkYjFkMjA2ODBmY2E2OTM3OGE3YTc2OGViNTMxYTY4MjYwNGNjOTAxNDNiOGE5NzhmMTQ2NWVhNzQ

Is the Slack community still open to the public?

**Comment by DanielJonesEB** [comment]
Thanks for the heads-up, that should now be fixed.
