### ISSUE TITLE
Control-tower-ops repo not accessible

### ISSUE THREAD

**Issue by jkbschmid** [EngineerBetter/control-tower#6]
The README states that [control-tower-ops](https://github.com/EngineerBetter/control-tower-ops) is required when building control-tower from source. However, the link to it https://github.com/EngineerBetter/control-tower-ops results in a 404. 
Is this a private repo perhaps?

**Comment by crsimmons** [comment]
Oops. We made that repo private. I'll go make it public. Sorry about that.

**Comment by crsimmons** [comment]
Should be accessible now @jkbschmid

**Comment by jkbschmid** [comment]
Wow, what a quick response. Thanks a lot :)
