### ISSUE TITLE
Letsencrypt integration documentation

### ISSUE THREAD

**Issue by lnhrdt** [EngineerBetter/control-tower#60]
The Features section in the Readme lists "Letsencrypt integration" but I can't find any information on it. I tried looking for mention of it in the "Detailed Documentation" and in the command line help.

Questions I have (as a new user) include:
- Is there anything I need to do to enable Letsencrypt integration?
- How to configure the Letsencrypt account email (for expiration notices)?
- Whether or not the Letsencrypt integration applies to the NATS certificate that expires in 1 year (mentioned in the [Maintain detailed documentation](https://github.com/EngineerBetter/control-tower/blob/master/docs/maintain.md)).

Could you help me with the answers to my questions or point me to any documentation I might have missed?

**Comment by crsimmons** [comment]
Thanks for the question @lnhrdt. This is a fairly old feature in the product that I'm hoping to improve when I get the chance.

This feature only impacts the certificate on the web vm. It does not generate any of the internal certs (like NATS) which are created using BOSH. We added that maintain command to help with rotating these certs.

When you deploy with Control Tower it will look at whether you are deploying with a domain and if you provided your own certs. If you provide a domain and don't provide your own certs then it will reach out to letsencrypt to get a cert for you. If you don't provide a domain it will just generate a self-signed cert instead.

Letsencrypt certs are only valid for a limited time (90 days I think) so we include a job in the self-update pipeline that will run periodically to renew your cert. There currently is no way to provide an email for the letsencrypt account.

**Comment by lnhrdt** [comment]
This information is very helpful @crsimmons, thank you.
