### ISSUE TITLE
Unable to set a domain (on GCP)

### ISSUE THREAD

**Issue by lnhrdt** [EngineerBetter/control-tower#61]
I've been unable to set a domain for my control-tower deployment on GCP. When I add the `--domain` flag to a deploy command like this:

```
GOOGLE_APPLICATION_CREDENTIALS=/path/to/creds.json \
  control-tower deploy \
  --iaas gcp \
  --region some-region \
  --github-auth-client-id XXX \
  --github-auth-client-secret YYY \
  --domain example.com \
  my-deployment
```

it always fails with:

>dns zone for domain 'example.com' was not found in cloudDNS.

Is that error message referring to GCP's [Cloud DNS](https://cloud.google.com/dns) service? I was planning on using my own DNS server for my domain. Is using Cloud DNS a requirement for setting a domain name for a control-tower deployment on GCP? What are my options and how do they work?

**Comment by crsimmons** [comment]
The domain you provide must fall within a hosted zone in the Cloud DNS of the GCP project you are deploying to. For example, in our system tests we test this by delegating `gcp.engineerbetter.com` to our GCP project (our root domain is managed on another DNS server) then specifying something like `control-tower.gcp.engineerbetter.com` as the domain.

This is sort of implied in [the note in our docs](https://github.com/EngineerBetter/control-tower/blob/master/docs/deploy.md#custom-domains) but it should be stated clearer. I'll add a clarification later.

**Comment by lnhrdt** [comment]
I missed that nuance in the docs until now. Thanks for clarifying it for for me and offering to add clarification to the docs for others. I agree it would be an improvement to say more plainly what a "hosted zone" entails on either GCP or AWS.

**Comment by crsimmons** [comment]
I've added to the docs https://github.com/EngineerBetter/control-tower/commit/85c2a6c9a11a56d31ec0f7b14d818e7a02b4b793

Closing this issue now. Please feel free to open another one if you run into further issues.
