### ISSUE TITLE
Unable to self-update Control Tower due to BOSH error

### ISSUE THREAD

**Issue by DMeechan** [EngineerBetter/control-tower#66]
We're currently running Control Tower `0.10.0` and have been trying to upgrade to `0.12.1` but the `self-update` job always fails on this step:

```bash
Task 112828 | 11:09:31 | Processing 1 existing job: Processing 1 existing job (00:00:00)
Task 112828 | 11:09:31 | Compiled Release has been created: telegraf-agent/1 (00:00:00)
Task 112824 | 11:09:56 | Creating new compiled packages: concourse/5d62dbcf6977f358f0ea925f8274b6c05d7a8376 for ubuntu-xenial/621.71 (00:00:45)
Task 112824 | 11:09:56 | Creating new compiled packages: btrfs_tools/797f8df53d2881f034366408b3f043a57f8f4c51 for ubuntu-xenial/621.71 (00:00:01)
Task 112824 | 11:09:57 | Creating new jobs: web/1d7d7ab29efce80f5e25f6d5ed46a20cce808fce (00:00:00)
Task 112824 | 11:09:57 | Processing 2 existing jobs: Processing 2 existing jobs (00:00:00)
Updating deployment:
  Expected task ‘112831’ to succeed but state is ‘error’
Task 112824 | 11:09:57 | Compiled Release has been created: concourse/6.0.0 (00:00:00)
Exit code 1
Task 112831 | 11:10:09 | Error: Failed to acquire lock for lock:deployment:concourse uid: de0ee4dc-d757-41a9-8096-094024a97b83. Locking task id is 112830, description: ‘scan and fix’

failed to run bosh deploy with commands [/tmp/control-tower192225347/concourse.yml --vars-store /tmp/control-tower192225347/concourse-creds.yml --ops-file /tmp/control-tower192225347/versions.json --ops-file /tmp/control-tower192225347/shas.json --ops-file /tmp/control-tower192225347/cup_compatibility.yml --vars-file /tmp/control-tower192225347/grafana_dashboard.yml --ops-file /tmp/control-tower192225347/github-auth.yml --ops-file /tmp/control-tower192225347/extra_tags.yml]: [Didn’t detect successful task start in BOSH comand: bosh-cli --non-interactive --environment https://xxx.xxx.xxx.xxx --deployment concourse deploy /tmp/control-tower192225347/concourse.yml …followed by a bunch of secrets and certificates…
```

On subsequent runs, the `self-update` job fails silently - the job goes green but the logs show it failed at a similar step:

```
Task 112868 | 11:47:32 | Update stemcell: Save stemcell bosh-aws-xen-hvm-ubuntu-xenial-go_agent/621.71 (ami-0bb13ca060086b2c6 light) (already exists, skipped) (00:00:00)

Task 112868 Started  Mon Jun  1 11:47:28 UTC 2020
Task 112868 Finished Mon Jun  1 11:47:32 UTC 2020
Task 112868 Duration 00:00:04
Task 112868 done

Succeeded

Task 112869 | 11:47:35 | Preparing deployment: Preparing deployment (00:02:16)
Task started, detaching output
Updating deployment:
  Expected task '112869' to succeed but state is 'error'
Exit code 1

UPGRADE RUNNING IN BACKGROUND
```

I tried manually updating control-tower via CLI a little while ago to see if that would yield a different outcome but I ran into the same issue there.

Any ideas on how to go about debugging this or fixes we can try?

**Comment by irbekrm** [comment]
Hi @DMeechan, 

Sorry to hear you're having issues with update!

We'll see if we can reproduce it.

Is your CT deployment on AWS or GCP?

**Comment by DMeechan** [comment]
Thanks @irbekrm! We're on AWS

**Comment by crsimmons** [comment]
`Locking task id is 112830, description: ‘scan and fix’` suggests that BOSH has determined something in your deployment is unhealthy and is trying to fix it automatically. If you target your director 

```
eval "$(control-tower info --iaas [AWS|GCP] --env <your-project-name>)"
```

then you can check the health of your VMs

```
bosh vms
```

and also what tasks are currently running

```
bosh tasks -a
```

you could also check what the locking task from your error was doing

```
bosh task 112830
```

You can temporarily turn off the resurrector which will prevent BOSH from running those scan and fix jobs which should allow you to run the update. Just don't forget to turn it back on after the update so that the platform can self-heal.

```
bosh update-resurrection off
```

**Comment by irbekrm** [comment]
I can also verify that for me the CT self update job (with update 0.10.0 -> 0.12.1) succeeded.

Let us know if it works?

**Comment by DMeechan** [comment]
Sorry it took a while to get back to you on this! When running `control-tower info <env>` I get this:

```bash
Error getting BOSH instances: Error [exit status 1] running `bosh instances`. stdout: [{
    "Tables": null,
    "Blocks": null,
    "Lines": [
        "Using environment 'https://xxx.xxx.xxx.xxx' as client 'admin'",
        "Listing deployment 'concourse' instances infos:\n  Director responded with non-successful status code '500' response ''",
        "Exit code 1"
    ]
}]
NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: some_request_id_here, host id: some_host_id_here
```

And a similar error when running `eval "$(control-tower info --iaas [AWS|GCP] --env <your-project-name>)"`:

```bash
NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: some_request_id_here, host id: some_host_id_here
```

Not too sure what next steps would be here.

I'm going to wipe and rebuild our Control Tower / Concourse environment on the latest versions since the `destroy` command still works and that'll probably be easier than trying to dive into it.

Thanks anyway for the help! Hopefully this might useful for anyone in the future who runs into a similar issue

**Comment by crsimmons** [comment]
@DMeechan when you deployed did you pass the `region` flag? If so you will need to provide the same region to the `info` command. The name of the config bucket contains the deployment region so if you don't provide one it assumes the default (eu-west-1).

**Comment by DMeechan** [comment]
@crsimmons Yep we use eu-west-1 and I had the env variables set:

```bash
export AWS_REGION=eu-west-1
export ZONE=eu-west-1a
```
