### ISSUE TITLE
Provide an option for encrypted disks on AWS

### ISSUE THREAD

**Issue by videlov** [EngineerBetter/control-tower#74]
We are using CT for managing our Concourse team pipelines (on an AWS account). Now we have the requirement to have all our volumes/disks encrypted. This is currently not supported via parameter or ops-file. We had to build custom dev version to solve this issue. Since we self-update our CT and update our instances in an automated fashion, could you provide such an option for AWS or enable it per default like in this branch change: 
https://github.com/videlov/control-tower/commit/55f4f5c46e0bcc1f5dea820f830bbda5f98c18ab

Best regards
@videlov

**Comment by crsimmons** [comment]
This should be implemented in the latest release https://github.com/EngineerBetter/control-tower/releases/tag/0.13.0. I couldn't think of a reason to let people not enable it so I just made it the hardcoded default.
