### ISSUE TITLE
[Feature-Request] Allow for CF uua authentication

### ISSUE THREAD

**Issue by EnorMOZ** [EngineerBetter/control-tower#79]
Allow for other authentication mechanism such as using a CF uua. There is currently a branch created with some work. Just wanted to make this feature request visible and trackable.

**Comment by crsimmons** [comment]
I did start implementing this on a branch. Looking at the changes I made I'm fairly confident it will work. The problem I had is not being able to test it. We don't have our own CF instance running and I couldn't find a cost effective way to spin one up in our test pipeline. I also considered just creating a UAA by itself but didn't get very far with that either.

I'd be interested to know if people would be okay with us adding untested features. I'm also open to suggestions of how we could test CF auth as part of our system tests.

**Comment by lcasey-aarp** [comment]
I can try to test this if you feel it is testable.  Will need to figure out how to build and go from there. If it helps I can try to provide an example from a real world pcf concourse bosh deployment pipeline. I know very little go to help from a code perspective. Its on one of my todo list to learn. Fell free to ping me on slack or discord.

**Comment by EnorMOZ** [comment]
I can try to test this. Need to figure out how to build it etc. If it will help can also provide a real world example from a pcf bosh deployment pipeline. Feel free to ping me on slack engineerbetter or concourse discord.

**Comment by EnorMOZ** [comment]
Pushed some changes to my fork. It is still a WIP. Requires further testing.

**Comment by EnorMOZ** [comment]
I am getting this at the end of each compile. `Succeeded
Get "": unsupported protocol scheme ""`
