### ISSUE TITLE
`auto_minor_version_upgrade` defaults to `true` and we can not self-update CT

### ISSUE THREAD

**Issue by videlov** [EngineerBetter/control-tower#84]
We have currently an issue when self-update our CT:

```
Error: Error applying plan:

1 error(s) occurred:

* aws_db_instance.default: 1 error(s) occurred:

* aws_db_instance.default: Error modifying DB Instance terraform-xxx: InvalidParameterCombination: Cannot upgrade postgres from 9.6.18 to 9.6.11
```

AWS had automatically upgraded our RDS instance, because default value for `auto_minor_version_upgrade ` in terraform for it is `true`:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#auto_minor_version_upgrade

A solution may be to set this property to this to `false` to prevent such an effect in the future, if you want to keep the hardcoded version. Meanwhile can we bump the hardcoded version to `9.6.18` so we fix our issue as well?

PR to review for this change:
https://github.com/EngineerBetter/control-tower/pull/83

Thanks
@videlov

**Comment by DanielJonesEB** [comment]
Thanks @videlov - we've been hit by this ourselves! The team are either all on billable work or virtually attending the CF Summit.

@andy-paine @crsimmons @irbekrm @will-gant If you get a chance, can you take a look at this as a priority over any bench work please?

**Comment by andy-paine** [comment]
Tested on a new install and updating our CT deployment and all looks good. It will take a few hours to clear our CI system then a new release will be cut.

Thanks for the contribution @videlov! 🎉

**Comment by crsimmons** [comment]
I just cut https://github.com/EngineerBetter/control-tower/releases/tag/0.13.4 with this change. Thanks again for the PR @videlov!
