### ISSUE TITLE
Control tower isn't creating new workers

### ISSUE THREAD

**Issue by slaterx** [EngineerBetter/control-tower#87]
Hi Team,

Great work on automating all this! Makes it very easy to try, very addictive indeed.

Unfortunately, using spot instances, if there's inactivity, the workers go to stalled state and do not come back at all. And, BOSH isn't starting new workers. I tried running deploy again to see if new workers get created but in the end the only solution is to destroy everything and start again. This is my deploy command:

```bash
control-tower deploy --iaas aws --region us-east-1 --domain ci.example.com --workers 12 \
--worker-type m4 --worker-size 4xlarge --web-size xlarge --db-size xlarge \
--vpc-network-range 10.49.0.0/16 --public-subnet-range 10.49.10.0/24 \
--private-subnet-range 10.49.20.0/24 --rds-subnet-range1 10.49.30.0/24 \
--rds-subnet-range2 10.49.40.0/24 ci
```

Also, I tried with less workers and `--spot=false`, but the machines ran out of disk space quite quickly...  and I couldn't find where to increase the disk sizes.

Would that be a bug?

Thanks,
Gleidson

**Comment by crsimmons** [comment]
We run our own Concourse using Control Tower on AWS using spot instances and haven't encountered this before. The worst we see is AWS killing the spots every few days but BOSH recreates them pretty quickly.

What do you mean by "inactivity"? BOSH/Concourse shouldn't care if anything is actually running on the workers.

When the workers stall what does bosh say is happening? i.e. `bosh vms`

Worker disk size is not something we currently expose as a configurable feature in Control Tower. It is set to 200GB for every worker size.

**Comment by DanielJonesEB** [comment]
Also - thanks for the kind words @slaterx

**Comment by slaterx** [comment]
Well, unfortunately I've been unable to reproduce this issue again to give more details about it. When I raised the ticket, `bosh vms` was listing a bunch of stale vms, but I did it again and this time spot vms are created to replace stale ones, it's all working fine now, so I'm closing the ticket.
