### ISSUE TITLE
renew-https-cert and manual deploy failed due to NATS cert expired.

### ISSUE THREAD

**Issue by huiz-psma** [EngineerBetter/control-tower#88]
This is the error message. 

`
Task 1422 | 12:16:27 | Error: An error has occurred while connecting to NATS: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

Task 1422 Started  Wed Jan 20 12:16:27 UTC 2021
Task 1422 Finished Wed Jan 20 12:16:27 UTC 2021
Task 1422 Duration 00:00:00
Task 1422 error

Updating deployment:
  Expected task '1422' to succeed but state is 'error'
`
Control-Tower version 0.13.5

Any way to get the cert redeployed/ skipped for NATS?

Thank you,
Hui

**Comment by crsimmons** [comment]
It sounds like one or more of the BOSH-generated certificates in your deployment has expired (most likely NATS). I've helped a few people solve this issue on slack in the past few weeks and I just pushed the steps we came up with to the docs.

Give [these troubleshooting steps](https://github.com/EngineerBetter/control-tower/blob/master/docs/troubleshooting.md#nats-certificate-is-expired) a go.

**Comment by huiz-psma** [comment]
Thank you. Let me give it a try after office hour.

**Comment by huiz-psma** [comment]
Thank you @crsimmons , I was able to update the cert. I did what's suggested by removing all certs form the director-creds.yml and did `control-tower deploy`. This recreated the bosh director as well as the web node and worker node but failed to finish. However, I couldn't export bosh credential with the error `NoSuchBucket: The specified bucket does not exist`. I exported the AWS_ACCESS_KEY and SECRET_KEY, but it didn't help. I accidentally run the deploy command one more time and it finished without error. So I guess we are good for 3 months now. Does the renew-https-cert task renew the NATS cert as well?

**Comment by crsimmons** [comment]
For the info command you might have been missing the `region` or `namespace` flags (depending on what you used to deploy in the first case). I'm glad you got it working in the end though.

The NATS cert is generated by BOSH and is valid for a year. The SSL cert generated by `renew-https-cert` is created with letsencrypt and will be valid for 90 days. They are not the same certificate.

**Comment by huiz-psma** [comment]
I did specify the region, but I was missing a name after `--env` which then took the deploy name as the input for env.

Reminder set for 1 year before the NATS cert expires. All good. This issue can be closed. Thank you.
