### ISSUE TITLE
Terraform tries to downgrade Postgres from 9.6.20 to 9.6.18

### ISSUE THREAD

**Issue by mikefox** [EngineerBetter/control-tower#93]
We were force by AWS to upgrade the version of Postgres that Control Tower was using because of a [security issue](https://www.postgresql.org/about/news/postgresql-131-125-1110-1015-9620-and-9524-released-2111/) in 9.6.18. Now when I attempt a deploy the Terraform config tries to downgrade Postgres from 9.6.20 to 9.6.18. This is preventing us from renewing the SSL certificate for the web server. Does anyone know a work around for this while we wait for the Postgres version to catch up?

**Comment by 46bit** [comment]
Hi @mikefox. Looks like we're specifying that version. Maybe submit a PR to alter https://github.com/EngineerBetter/control-tower/blob/20a1b4594f05b47b368fd2768332170f7d8783c6/resource/assets/aws/infrastructure.tf#L593

**Comment by mikefox** [comment]
@46bit Thanks, I've done that [here](https://github.com/EngineerBetter/control-tower/pull/94). Is there anything else I can do to speed up the release of this so we can use the updated version?

**Comment by DanielJonesEB** [comment]
@mikefox Afraid not - we've got some Bionic updates blocking the pipeline currently (stemcell works for the deploymewnt itself, but not for the BOSH Director), and everyone's assigned to billable work. What might be quicker if you're in a sticky situation is building from source?

**Comment by BooleanCat** [comment]
Hey there @mikefox - we've just shipped [Control Tower 0.16.19](https://github.com/EngineerBetter/control-tower/releases/tag/0.16.19), which uses AWS Postgres 9.6.21. Thanks for bringing this to our attention 👍🏻

**Comment by mikefox** [comment]
@BooleanCat Awesome. Thanks for the swift turn around!
