### ISSUE TITLE
Update bosh ci to at least 5.2.1

### ISSUE THREAD

**Issue by pieterjanpintens** [EngineerBetter/control-tower#95]
Hi, we have been using control tower for some time and we were planning on running the update.
But we keep hitting a bug in the bosh ci:
https://github.com/cloudfoundry/bosh-cli/issues/462

Currently we are changed to version to 5.2.1, rebuild control tower and run with that. This seems to work.

**Comment by DanielJonesEB** [comment]
Thanks for raising the issue @pieterjanpintens! I hadn't realised that we hadn't automated new versions of the CLIs. I've got a vague recollection that we might have been bitten by a Terraform upgrade at some point in the past, but I could be imagining it.

@BooleanCat has kindly picked this up this morning, so hopefully we'll have a release if it goes through the pipeline cleanly.

Is the organisation you use Concourse in listed on [the Concourse website Ecosystem page](https://concourse-ci.org/ecosystem.html)? If not, would you consider raising a PR to add it? With a lot of internal shuffles at VMware, it'd be great if the folks in charge could see how widely used the tool is.

**Comment by friegger** [comment]
@BooleanCat, you bumped to `5.5.1` with https://github.com/EngineerBetter/control-tower-ops/commit/692ed91d1807a4e216432f12a387d67fc166509c which certainly fixes this issue. Nevertheless, I wonder is there something specific blocking you from upgrading to the latest 6.x bosh cli version? Only breaking change seems to be removal of [no-op --force](https://github.com/cloudfoundry/bosh-cli/releases/tag/v6.0.0) flags.

**Comment by friegger** [comment]
No, regarding this specific issue with the bosh cli we were able to create a dev release of control-tower and that worked just fine. Thanks for having that documented well by the way.

**Comment by DanielJonesEB** [comment]
Cool, glad that it's not causing a blocker @friegger. Looks like we'll be forking the release in question, so might be able to sort this next week.

**Comment by DanielJonesEB** [comment]
> Thanks for having that documented well by the way.

Oh, that's all the hard fork of @crsimmons I believe!

**Comment by BooleanCat** [comment]
I've just shipped [0.16.24](https://github.com/EngineerBetter/control-tower/releases/tag/0.16.24) with bosh cli 5.5.1.

> Nevertheless, I wonder is there something specific blocking you from upgrading to the latest 6.x bosh cli version? 

Nothing specific other than "that looks like a major version bump and I don't have time to read through release notes atm". I kinda hoped the bump to 5.5.1 would be fire and forget (which it turned out not to be for other reasons!).

Thanks for bringing this to our attention @pieterjanpintens
